DELETE http://localhost:3001/api/persons/3
###
DELETE http://localhost:3001/api/persons/69ae8bcc090633b5eb761da2
###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name": "Adamantis",
    "number": "10-22-31",
    "id": "999999999999"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name": "Carl",
    "number": "12-22-31",
    "id": "999999999999"
}

###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name": "Ca",
    "number": "12-22-31",
    "id": "999999999999"
}
###
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "number": "10-22-31",
    "id": "999999999999"
}